name: my first workflow
on:
  pull_request:
  push:
    branches:
      - main  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Printing Message
        run: echo "Hello world from PR"