name: Day 5 workflow
on:
  schedule:
    # Runs every day at 9:00 AM UTC
    - cron: '0 9 * * *'
  pull_request:
  push:
    branches:
      - main  
  workflow_dispatch:
    inputs:
      environment:
        description: 'Target environment'
        required: true
        type: choice
        options:
          - staging
          - production    
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Printing the message
        run: echo "validate successful"

  security:
    needs: validate
    runs-on: ubuntu-latest
    steps:
      - name: Printing the message
        run: echo "security successful"

  build:
    needs: security  
    runs-on: ubuntu-latest
    steps:
      - name: Printing the message
        run: echo "build successful"

         