name: Secret Example
on: push

jobs:
  secret-demo:
    runs-on: ubuntu-latest
    steps:
      
      - name: Use Secret
        
        run: echo "API Key is ${{ secrets.MY_API_KEY }}"

      # Pass secret as an input to an action
      - name: Print actor
        run: echo "${{ github.actor }}"