name: Day 8 - Actions and Marketplace

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/day8.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4   

      - name: list the files on runner
        run: ls -la  